name: 'Tag Creator'
description: 'Create a new version with the number from the input.'
inputs:
  new-version:
    description: 'This is the new version if non is added we will bump the last one.'
    required: false
    default: null
outputs:
  link:
    description: 'The link to the new version'
runs:
  using: 'node14'
  main: 'index.js'